version: '3.8'

services:
  smrpo-api:
    container_name: smrpo-api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api:${HTTP_PORT:-3000}" ]
    depends_on:
      - smrpo-db
    env_file:
      - .env

  smrpo-db:
    image: postgres:15-alpine
    container_name: smrpo-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}" ]
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=sl-SI"
      LANG: sl_SI.utf8
      TZ: 'Europe/Ljubljana'
    volumes:
      - postgres:/var/lib/postgresql/data

  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - smrpo-db

volumes:
  postgres:
    name: smrpo-db
