version: '3.8'
name: smrpo
services:
  smrpo-api:
    container_name: smrpo-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api:${HTTP_PORT:-3000}" ]
    depends_on:
      - smrpo-db
    env_file:
      - .env

  smrpo-db:
    image: postgres:15.1-alpine
    container_name: smrpo-db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}" ]
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: smrpo-db
