version: '3.8'
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER}" ]
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: db
