-- AlterTable
ALTER TABLE "Sprint" ALTER COLUMN "velocity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Task" ALTER COLUMN "hours" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserStory" ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;
